#ifndef TYM_INTERNAL_CHARSET_H
#define TYM_INTERNAL_CHARSET_H

enum tym_i_charset_type {
  TYM_I_CHARSET_USASCII,
  TYM_I_CHARSET_DEC_SPECIAL_CHARACTER_AND_LINE_DRAWING_SET,
  TYM_I_CHARSET_UK,
  TYM_I_CHARSET_DUTCH,
  TYM_I_CHARSET_FINNISH,
  TYM_I_CHARSET_FRENCH,
  TYM_I_CHARSET_FRENCH_CANADIAN,
  TYM_I_CHARSET_GERMAN,
  TYM_I_CHARSET_ITALIAN,
  TYM_I_CHARSET_NORWEGIAN_DANISH,
  TYM_I_CHARSET_SPANISH,
  TYM_I_CHARSET_SWEDISH,
  TYM_I_CHARSET_SWISS,
  TYM_I_CHARSET_DEFAULT = 0, // TODO: Put the correct charset first.
};

#endif
